// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: deal.proto

package leadexchangev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _deal_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Deal with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Deal) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Deal with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DealMultiError, or nil if none found.
func (m *Deal) ValidateAll() error {
	return m.validate(true)
}

func (m *Deal) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DealId

	if err := m._validateUuid(m.GetLeadId()); err != nil {
		err = DealValidationError{
			field:  "LeadId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetSellerUserId()); err != nil {
		err = DealValidationError{
			field:  "SellerUserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for BuyerUserId

	if m.GetPrice() <= 0 {
		err := DealValidationError{
			field:  "Price",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return DealMultiError(errors)
	}

	return nil
}

func (m *Deal) _validateUuid(uuid string) error {
	if matched := _deal_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// DealMultiError is an error wrapping multiple validation errors returned by
// Deal.ValidateAll() if the designated constraints aren't met.
type DealMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DealMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DealMultiError) AllErrors() []error { return m }

// DealValidationError is the validation error returned by Deal.Validate if the
// designated constraints aren't met.
type DealValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DealValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DealValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DealValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DealValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DealValidationError) ErrorName() string { return "DealValidationError" }

// Error satisfies the builtin error interface
func (e DealValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeal.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DealValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DealValidationError{}

// Validate checks the field values on CreateDealRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateDealRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateDealRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateDealRequestMultiError, or nil if none found.
func (m *CreateDealRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateDealRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetLeadId()); err != nil {
		err = CreateDealRequestValidationError{
			field:  "LeadId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPrice() <= 0 {
		err := CreateDealRequestValidationError{
			field:  "Price",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateDealRequestMultiError(errors)
	}

	return nil
}

func (m *CreateDealRequest) _validateUuid(uuid string) error {
	if matched := _deal_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// CreateDealRequestMultiError is an error wrapping multiple validation errors
// returned by CreateDealRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateDealRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateDealRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateDealRequestMultiError) AllErrors() []error { return m }

// CreateDealRequestValidationError is the validation error returned by
// CreateDealRequest.Validate if the designated constraints aren't met.
type CreateDealRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateDealRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateDealRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateDealRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateDealRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateDealRequestValidationError) ErrorName() string {
	return "CreateDealRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateDealRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateDealRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateDealRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateDealRequestValidationError{}

// Validate checks the field values on GetDealRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetDealRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDealRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetDealRequestMultiError,
// or nil if none found.
func (m *GetDealRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDealRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetDealId()); err != nil {
		err = GetDealRequestValidationError{
			field:  "DealId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetDealRequestMultiError(errors)
	}

	return nil
}

func (m *GetDealRequest) _validateUuid(uuid string) error {
	if matched := _deal_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetDealRequestMultiError is an error wrapping multiple validation errors
// returned by GetDealRequest.ValidateAll() if the designated constraints
// aren't met.
type GetDealRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDealRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDealRequestMultiError) AllErrors() []error { return m }

// GetDealRequestValidationError is the validation error returned by
// GetDealRequest.Validate if the designated constraints aren't met.
type GetDealRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDealRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDealRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDealRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDealRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDealRequestValidationError) ErrorName() string { return "GetDealRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetDealRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDealRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDealRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDealRequestValidationError{}

// Validate checks the field values on ListDealsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListDealsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDealsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDealsRequestMultiError, or nil if none found.
func (m *ListDealsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDealsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFilter()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListDealsRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListDealsRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilter()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListDealsRequestValidationError{
				field:  "Filter",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListDealsRequestMultiError(errors)
	}

	return nil
}

// ListDealsRequestMultiError is an error wrapping multiple validation errors
// returned by ListDealsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListDealsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDealsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDealsRequestMultiError) AllErrors() []error { return m }

// ListDealsRequestValidationError is the validation error returned by
// ListDealsRequest.Validate if the designated constraints aren't met.
type ListDealsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDealsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDealsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDealsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDealsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDealsRequestValidationError) ErrorName() string { return "ListDealsRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListDealsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDealsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDealsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDealsRequestValidationError{}

// Validate checks the field values on ListDealsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListDealsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDealsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDealsResponseMultiError, or nil if none found.
func (m *ListDealsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDealsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetDeals() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListDealsResponseValidationError{
						field:  fmt.Sprintf("Deals[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListDealsResponseValidationError{
						field:  fmt.Sprintf("Deals[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListDealsResponseValidationError{
					field:  fmt.Sprintf("Deals[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListDealsResponseMultiError(errors)
	}

	return nil
}

// ListDealsResponseMultiError is an error wrapping multiple validation errors
// returned by ListDealsResponse.ValidateAll() if the designated constraints
// aren't met.
type ListDealsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDealsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDealsResponseMultiError) AllErrors() []error { return m }

// ListDealsResponseValidationError is the validation error returned by
// ListDealsResponse.Validate if the designated constraints aren't met.
type ListDealsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDealsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDealsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDealsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDealsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDealsResponseValidationError) ErrorName() string {
	return "ListDealsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListDealsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDealsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDealsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDealsResponseValidationError{}

// Validate checks the field values on UpdateDealRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateDealRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateDealRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateDealRequestMultiError, or nil if none found.
func (m *UpdateDealRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateDealRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetDealId()); err != nil {
		err = UpdateDealRequestValidationError{
			field:  "DealId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if m.Price != nil {
		// no validation rules for Price
	}

	if len(errors) > 0 {
		return UpdateDealRequestMultiError(errors)
	}

	return nil
}

func (m *UpdateDealRequest) _validateUuid(uuid string) error {
	if matched := _deal_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// UpdateDealRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateDealRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateDealRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateDealRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateDealRequestMultiError) AllErrors() []error { return m }

// UpdateDealRequestValidationError is the validation error returned by
// UpdateDealRequest.Validate if the designated constraints aren't met.
type UpdateDealRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateDealRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateDealRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateDealRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateDealRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateDealRequestValidationError) ErrorName() string {
	return "UpdateDealRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateDealRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateDealRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateDealRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateDealRequestValidationError{}

// Validate checks the field values on AcceptDealRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AcceptDealRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AcceptDealRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AcceptDealRequestMultiError, or nil if none found.
func (m *AcceptDealRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AcceptDealRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetDealId()); err != nil {
		err = AcceptDealRequestValidationError{
			field:  "DealId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AcceptDealRequestMultiError(errors)
	}

	return nil
}

func (m *AcceptDealRequest) _validateUuid(uuid string) error {
	if matched := _deal_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// AcceptDealRequestMultiError is an error wrapping multiple validation errors
// returned by AcceptDealRequest.ValidateAll() if the designated constraints
// aren't met.
type AcceptDealRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AcceptDealRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AcceptDealRequestMultiError) AllErrors() []error { return m }

// AcceptDealRequestValidationError is the validation error returned by
// AcceptDealRequest.Validate if the designated constraints aren't met.
type AcceptDealRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AcceptDealRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AcceptDealRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AcceptDealRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AcceptDealRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AcceptDealRequestValidationError) ErrorName() string {
	return "AcceptDealRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AcceptDealRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAcceptDealRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AcceptDealRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AcceptDealRequestValidationError{}

// Validate checks the field values on DealResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DealResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DealResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DealResponseMultiError, or
// nil if none found.
func (m *DealResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DealResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDeal()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DealResponseValidationError{
					field:  "Deal",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DealResponseValidationError{
					field:  "Deal",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeal()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DealResponseValidationError{
				field:  "Deal",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DealResponseMultiError(errors)
	}

	return nil
}

// DealResponseMultiError is an error wrapping multiple validation errors
// returned by DealResponse.ValidateAll() if the designated constraints aren't met.
type DealResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DealResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DealResponseMultiError) AllErrors() []error { return m }

// DealResponseValidationError is the validation error returned by
// DealResponse.Validate if the designated constraints aren't met.
type DealResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DealResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DealResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DealResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DealResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DealResponseValidationError) ErrorName() string { return "DealResponseValidationError" }

// Error satisfies the builtin error interface
func (e DealResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDealResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DealResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DealResponseValidationError{}

// Validate checks the field values on ListDealsRequest_Filter with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListDealsRequest_Filter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDealsRequest_Filter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDealsRequest_FilterMultiError, or nil if none found.
func (m *ListDealsRequest_Filter) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDealsRequest_Filter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.LeadId != nil {
		// no validation rules for LeadId
	}

	if m.SellerUserId != nil {
		// no validation rules for SellerUserId
	}

	if m.BuyerUserId != nil {
		// no validation rules for BuyerUserId
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if m.MinPrice != nil {
		// no validation rules for MinPrice
	}

	if m.MaxPrice != nil {
		// no validation rules for MaxPrice
	}

	if len(errors) > 0 {
		return ListDealsRequest_FilterMultiError(errors)
	}

	return nil
}

// ListDealsRequest_FilterMultiError is an error wrapping multiple validation
// errors returned by ListDealsRequest_Filter.ValidateAll() if the designated
// constraints aren't met.
type ListDealsRequest_FilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDealsRequest_FilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDealsRequest_FilterMultiError) AllErrors() []error { return m }

// ListDealsRequest_FilterValidationError is the validation error returned by
// ListDealsRequest_Filter.Validate if the designated constraints aren't met.
type ListDealsRequest_FilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDealsRequest_FilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDealsRequest_FilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDealsRequest_FilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDealsRequest_FilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDealsRequest_FilterValidationError) ErrorName() string {
	return "ListDealsRequest_FilterValidationError"
}

// Error satisfies the builtin error interface
func (e ListDealsRequest_FilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDealsRequest_Filter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDealsRequest_FilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDealsRequest_FilterValidationError{}
