// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: deal.proto

package leadexchangev1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DealStatus — статус сделки.
type DealStatus int32

const (
	// Не задан (значение по умолчанию, не используется)
	DealStatus_DEAL_STATUS_UNSPECIFIED DealStatus = 0
	// Создана, ожидает покупателя
	DealStatus_DEAL_STATUS_PENDING DealStatus = 1
	// Принята покупателем
	DealStatus_DEAL_STATUS_ACCEPTED DealStatus = 2
	// Завершена (лид передан)
	DealStatus_DEAL_STATUS_COMPLETED DealStatus = 3
	// Отменена продавцом
	DealStatus_DEAL_STATUS_CANCELLED DealStatus = 4
	// Отклонена покупателем
	DealStatus_DEAL_STATUS_REJECTED DealStatus = 5
)

// Enum value maps for DealStatus.
var (
	DealStatus_name = map[int32]string{
		0: "DEAL_STATUS_UNSPECIFIED",
		1: "DEAL_STATUS_PENDING",
		2: "DEAL_STATUS_ACCEPTED",
		3: "DEAL_STATUS_COMPLETED",
		4: "DEAL_STATUS_CANCELLED",
		5: "DEAL_STATUS_REJECTED",
	}
	DealStatus_value = map[string]int32{
		"DEAL_STATUS_UNSPECIFIED": 0,
		"DEAL_STATUS_PENDING":     1,
		"DEAL_STATUS_ACCEPTED":    2,
		"DEAL_STATUS_COMPLETED":   3,
		"DEAL_STATUS_CANCELLED":   4,
		"DEAL_STATUS_REJECTED":    5,
	}
)

func (x DealStatus) Enum() *DealStatus {
	p := new(DealStatus)
	*p = x
	return p
}

func (x DealStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DealStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_deal_proto_enumTypes[0].Descriptor()
}

func (DealStatus) Type() protoreflect.EnumType {
	return &file_deal_proto_enumTypes[0]
}

func (x DealStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DealStatus.Descriptor instead.
func (DealStatus) EnumDescriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{0}
}

// Deal — сущность сделки.
type Deal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID сделки
	DealId string `protobuf:"bytes,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	// UUID лида, который продаётся
	LeadId string `protobuf:"bytes,2,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	// UUID продавца
	SellerUserId string `protobuf:"bytes,3,opt,name=seller_user_id,json=sellerUserId,proto3" json:"seller_user_id,omitempty"`
	// UUID покупателя (может быть пустым, если сделка ещё не принята)
	BuyerUserId string `protobuf:"bytes,4,opt,name=buyer_user_id,json=buyerUserId,proto3" json:"buyer_user_id,omitempty"`
	// Цена сделки
	Price float64 `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	// Статус сделки
	Status        DealStatus `protobuf:"varint,6,opt,name=status,proto3,enum=leadexchange.v1.DealStatus" json:"status,omitempty"`
	CreatedAt     string     `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string     `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deal) Reset() {
	*x = Deal{}
	mi := &file_deal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deal) ProtoMessage() {}

func (x *Deal) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deal.ProtoReflect.Descriptor instead.
func (*Deal) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{0}
}

func (x *Deal) GetDealId() string {
	if x != nil {
		return x.DealId
	}
	return ""
}

func (x *Deal) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *Deal) GetSellerUserId() string {
	if x != nil {
		return x.SellerUserId
	}
	return ""
}

func (x *Deal) GetBuyerUserId() string {
	if x != nil {
		return x.BuyerUserId
	}
	return ""
}

func (x *Deal) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Deal) GetStatus() DealStatus {
	if x != nil {
		return x.Status
	}
	return DealStatus_DEAL_STATUS_UNSPECIFIED
}

func (x *Deal) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Deal) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateDealRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID лида, который продаётся
	LeadId string `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	// Цена сделки
	Price         float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDealRequest) Reset() {
	*x = CreateDealRequest{}
	mi := &file_deal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDealRequest) ProtoMessage() {}

func (x *CreateDealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDealRequest.ProtoReflect.Descriptor instead.
func (*CreateDealRequest) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDealRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *CreateDealRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetDealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DealId        string                 `protobuf:"bytes,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDealRequest) Reset() {
	*x = GetDealRequest{}
	mi := &file_deal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDealRequest) ProtoMessage() {}

func (x *GetDealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDealRequest.ProtoReflect.Descriptor instead.
func (*GetDealRequest) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{2}
}

func (x *GetDealRequest) GetDealId() string {
	if x != nil {
		return x.DealId
	}
	return ""
}

type ListDealsRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Filter        *ListDealsRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDealsRequest) Reset() {
	*x = ListDealsRequest{}
	mi := &file_deal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDealsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDealsRequest) ProtoMessage() {}

func (x *ListDealsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDealsRequest.ProtoReflect.Descriptor instead.
func (*ListDealsRequest) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{3}
}

func (x *ListDealsRequest) GetFilter() *ListDealsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListDealsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deals         []*Deal                `protobuf:"bytes,1,rep,name=deals,proto3" json:"deals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDealsResponse) Reset() {
	*x = ListDealsResponse{}
	mi := &file_deal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDealsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDealsResponse) ProtoMessage() {}

func (x *ListDealsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDealsResponse.ProtoReflect.Descriptor instead.
func (*ListDealsResponse) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{4}
}

func (x *ListDealsResponse) GetDeals() []*Deal {
	if x != nil {
		return x.Deals
	}
	return nil
}

type UpdateDealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DealId        string                 `protobuf:"bytes,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	Status        *DealStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=leadexchange.v1.DealStatus,oneof" json:"status,omitempty"`
	Price         *float64               `protobuf:"fixed64,3,opt,name=price,proto3,oneof" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDealRequest) Reset() {
	*x = UpdateDealRequest{}
	mi := &file_deal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDealRequest) ProtoMessage() {}

func (x *UpdateDealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDealRequest.ProtoReflect.Descriptor instead.
func (*UpdateDealRequest) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDealRequest) GetDealId() string {
	if x != nil {
		return x.DealId
	}
	return ""
}

func (x *UpdateDealRequest) GetStatus() DealStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return DealStatus_DEAL_STATUS_UNSPECIFIED
}

func (x *UpdateDealRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

type AcceptDealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DealId        string                 `protobuf:"bytes,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptDealRequest) Reset() {
	*x = AcceptDealRequest{}
	mi := &file_deal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptDealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptDealRequest) ProtoMessage() {}

func (x *AcceptDealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptDealRequest.ProtoReflect.Descriptor instead.
func (*AcceptDealRequest) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptDealRequest) GetDealId() string {
	if x != nil {
		return x.DealId
	}
	return ""
}

type DealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deal          *Deal                  `protobuf:"bytes,1,opt,name=deal,proto3" json:"deal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealResponse) Reset() {
	*x = DealResponse{}
	mi := &file_deal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealResponse) ProtoMessage() {}

func (x *DealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealResponse.ProtoReflect.Descriptor instead.
func (*DealResponse) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{7}
}

func (x *DealResponse) GetDeal() *Deal {
	if x != nil {
		return x.Deal
	}
	return nil
}

type ListDealsRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadId        *string                `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3,oneof" json:"lead_id,omitempty"`
	SellerUserId  *string                `protobuf:"bytes,2,opt,name=seller_user_id,json=sellerUserId,proto3,oneof" json:"seller_user_id,omitempty"`
	BuyerUserId   *string                `protobuf:"bytes,3,opt,name=buyer_user_id,json=buyerUserId,proto3,oneof" json:"buyer_user_id,omitempty"`
	Status        *DealStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=leadexchange.v1.DealStatus,oneof" json:"status,omitempty"`
	MinPrice      *float64               `protobuf:"fixed64,5,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *float64               `protobuf:"fixed64,6,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDealsRequest_Filter) Reset() {
	*x = ListDealsRequest_Filter{}
	mi := &file_deal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDealsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDealsRequest_Filter) ProtoMessage() {}

func (x *ListDealsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDealsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListDealsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListDealsRequest_Filter) GetLeadId() string {
	if x != nil && x.LeadId != nil {
		return *x.LeadId
	}
	return ""
}

func (x *ListDealsRequest_Filter) GetSellerUserId() string {
	if x != nil && x.SellerUserId != nil {
		return *x.SellerUserId
	}
	return ""
}

func (x *ListDealsRequest_Filter) GetBuyerUserId() string {
	if x != nil && x.BuyerUserId != nil {
		return *x.BuyerUserId
	}
	return ""
}

func (x *ListDealsRequest_Filter) GetStatus() DealStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return DealStatus_DEAL_STATUS_UNSPECIFIED
}

func (x *ListDealsRequest_Filter) GetMinPrice() float64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *ListDealsRequest_Filter) GetMaxPrice() float64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

var File_deal_proto protoreflect.FileDescriptor

const file_deal_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"deal.proto\x12\x0fleadexchange.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xaf\x02\n" +
	"\x04Deal\x12\x17\n" +
	"\adeal_id\x18\x01 \x01(\tR\x06dealId\x12!\n" +
	"\alead_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06leadId\x12.\n" +
	"\x0eseller_user_id\x18\x03 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\fsellerUserId\x12\"\n" +
	"\rbuyer_user_id\x18\x04 \x01(\tR\vbuyerUserId\x12$\n" +
	"\x05price\x18\x05 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x05price\x123\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.leadexchange.v1.DealStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\\\n" +
	"\x11CreateDealRequest\x12!\n" +
	"\alead_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06leadId\x12$\n" +
	"\x05price\x18\x02 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x05price\"3\n" +
	"\x0eGetDealRequest\x12!\n" +
	"\adeal_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06dealId\"\xa7\x03\n" +
	"\x10ListDealsRequest\x12@\n" +
	"\x06filter\x18\x01 \x01(\v2(.leadexchange.v1.ListDealsRequest.FilterR\x06filter\x1a\xd0\x02\n" +
	"\x06Filter\x12\x1c\n" +
	"\alead_id\x18\x01 \x01(\tH\x00R\x06leadId\x88\x01\x01\x12)\n" +
	"\x0eseller_user_id\x18\x02 \x01(\tH\x01R\fsellerUserId\x88\x01\x01\x12'\n" +
	"\rbuyer_user_id\x18\x03 \x01(\tH\x02R\vbuyerUserId\x88\x01\x01\x128\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.leadexchange.v1.DealStatusH\x03R\x06status\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\x05 \x01(\x01H\x04R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\x06 \x01(\x01H\x05R\bmaxPrice\x88\x01\x01B\n" +
	"\n" +
	"\b_lead_idB\x11\n" +
	"\x0f_seller_user_idB\x10\n" +
	"\x0e_buyer_user_idB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_price\"@\n" +
	"\x11ListDealsResponse\x12+\n" +
	"\x05deals\x18\x01 \x03(\v2\x15.leadexchange.v1.DealR\x05deals\"\xa0\x01\n" +
	"\x11UpdateDealRequest\x12!\n" +
	"\adeal_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06dealId\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.leadexchange.v1.DealStatusH\x00R\x06status\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x03 \x01(\x01H\x01R\x05price\x88\x01\x01B\t\n" +
	"\a_statusB\b\n" +
	"\x06_price\"6\n" +
	"\x11AcceptDealRequest\x12!\n" +
	"\adeal_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06dealId\"9\n" +
	"\fDealResponse\x12)\n" +
	"\x04deal\x18\x01 \x01(\v2\x15.leadexchange.v1.DealR\x04deal*\xac\x01\n" +
	"\n" +
	"DealStatus\x12\x1b\n" +
	"\x17DEAL_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DEAL_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14DEAL_STATUS_ACCEPTED\x10\x02\x12\x19\n" +
	"\x15DEAL_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15DEAL_STATUS_CANCELLED\x10\x04\x12\x18\n" +
	"\x14DEAL_STATUS_REJECTED\x10\x052\xac\x04\n" +
	"\vDealService\x12e\n" +
	"\n" +
	"CreateDeal\x12\".leadexchange.v1.CreateDealRequest\x1a\x1d.leadexchange.v1.DealResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/deals\x12f\n" +
	"\aGetDeal\x12\x1f.leadexchange.v1.GetDealRequest\x1a\x1d.leadexchange.v1.DealResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/deals/{deal_id}\x12e\n" +
	"\tListDeals\x12!.leadexchange.v1.ListDealsRequest\x1a\".leadexchange.v1.ListDealsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/deals\x12o\n" +
	"\n" +
	"UpdateDeal\x12\".leadexchange.v1.UpdateDealRequest\x1a\x1d.leadexchange.v1.DealResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*2\x13/v1/deals/{deal_id}\x12v\n" +
	"\n" +
	"AcceptDeal\x12\".leadexchange.v1.AcceptDealRequest\x1a\x1d.leadexchange.v1.DealResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/deals/{deal_id}/acceptB4Z2leadexchange/gen/go/leadexchange/v1;leadexchangev1b\x06proto3"

var (
	file_deal_proto_rawDescOnce sync.Once
	file_deal_proto_rawDescData []byte
)

func file_deal_proto_rawDescGZIP() []byte {
	file_deal_proto_rawDescOnce.Do(func() {
		file_deal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deal_proto_rawDesc), len(file_deal_proto_rawDesc)))
	})
	return file_deal_proto_rawDescData
}

var file_deal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_deal_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_deal_proto_goTypes = []any{
	(DealStatus)(0),                 // 0: leadexchange.v1.DealStatus
	(*Deal)(nil),                    // 1: leadexchange.v1.Deal
	(*CreateDealRequest)(nil),       // 2: leadexchange.v1.CreateDealRequest
	(*GetDealRequest)(nil),          // 3: leadexchange.v1.GetDealRequest
	(*ListDealsRequest)(nil),        // 4: leadexchange.v1.ListDealsRequest
	(*ListDealsResponse)(nil),       // 5: leadexchange.v1.ListDealsResponse
	(*UpdateDealRequest)(nil),       // 6: leadexchange.v1.UpdateDealRequest
	(*AcceptDealRequest)(nil),       // 7: leadexchange.v1.AcceptDealRequest
	(*DealResponse)(nil),            // 8: leadexchange.v1.DealResponse
	(*ListDealsRequest_Filter)(nil), // 9: leadexchange.v1.ListDealsRequest.Filter
}
var file_deal_proto_depIdxs = []int32{
	0,  // 0: leadexchange.v1.Deal.status:type_name -> leadexchange.v1.DealStatus
	9,  // 1: leadexchange.v1.ListDealsRequest.filter:type_name -> leadexchange.v1.ListDealsRequest.Filter
	1,  // 2: leadexchange.v1.ListDealsResponse.deals:type_name -> leadexchange.v1.Deal
	0,  // 3: leadexchange.v1.UpdateDealRequest.status:type_name -> leadexchange.v1.DealStatus
	1,  // 4: leadexchange.v1.DealResponse.deal:type_name -> leadexchange.v1.Deal
	0,  // 5: leadexchange.v1.ListDealsRequest.Filter.status:type_name -> leadexchange.v1.DealStatus
	2,  // 6: leadexchange.v1.DealService.CreateDeal:input_type -> leadexchange.v1.CreateDealRequest
	3,  // 7: leadexchange.v1.DealService.GetDeal:input_type -> leadexchange.v1.GetDealRequest
	4,  // 8: leadexchange.v1.DealService.ListDeals:input_type -> leadexchange.v1.ListDealsRequest
	6,  // 9: leadexchange.v1.DealService.UpdateDeal:input_type -> leadexchange.v1.UpdateDealRequest
	7,  // 10: leadexchange.v1.DealService.AcceptDeal:input_type -> leadexchange.v1.AcceptDealRequest
	8,  // 11: leadexchange.v1.DealService.CreateDeal:output_type -> leadexchange.v1.DealResponse
	8,  // 12: leadexchange.v1.DealService.GetDeal:output_type -> leadexchange.v1.DealResponse
	5,  // 13: leadexchange.v1.DealService.ListDeals:output_type -> leadexchange.v1.ListDealsResponse
	8,  // 14: leadexchange.v1.DealService.UpdateDeal:output_type -> leadexchange.v1.DealResponse
	8,  // 15: leadexchange.v1.DealService.AcceptDeal:output_type -> leadexchange.v1.DealResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_deal_proto_init() }
func file_deal_proto_init() {
	if File_deal_proto != nil {
		return
	}
	file_deal_proto_msgTypes[5].OneofWrappers = []any{}
	file_deal_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deal_proto_rawDesc), len(file_deal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deal_proto_goTypes,
		DependencyIndexes: file_deal_proto_depIdxs,
		EnumInfos:         file_deal_proto_enumTypes,
		MessageInfos:      file_deal_proto_msgTypes,
	}.Build()
	File_deal_proto = out.File
	file_deal_proto_goTypes = nil
	file_deal_proto_depIdxs = nil
}
