// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: deal.proto

package leadexchangev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DealService_CreateDeal_FullMethodName = "/leadexchange.v1.DealService/CreateDeal"
	DealService_GetDeal_FullMethodName    = "/leadexchange.v1.DealService/GetDeal"
	DealService_ListDeals_FullMethodName  = "/leadexchange.v1.DealService/ListDeals"
	DealService_UpdateDeal_FullMethodName = "/leadexchange.v1.DealService/UpdateDeal"
	DealService_AcceptDeal_FullMethodName = "/leadexchange.v1.DealService/AcceptDeal"
)

// DealServiceClient is the client API for DealService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DealServiceClient interface {
	// Создать новую сделку.
	CreateDeal(ctx context.Context, in *CreateDealRequest, opts ...grpc.CallOption) (*DealResponse, error)
	// Получить информацию о конкретной сделке.
	GetDeal(ctx context.Context, in *GetDealRequest, opts ...grpc.CallOption) (*DealResponse, error)
	// Получить список сделок по фильтру.
	ListDeals(ctx context.Context, in *ListDealsRequest, opts ...grpc.CallOption) (*ListDealsResponse, error)
	// Обновить сделку (принять, отклонить, отменить, завершить).
	UpdateDeal(ctx context.Context, in *UpdateDealRequest, opts ...grpc.CallOption) (*DealResponse, error)
	// Принять сделку (покупатель принимает предложение).
	AcceptDeal(ctx context.Context, in *AcceptDealRequest, opts ...grpc.CallOption) (*DealResponse, error)
}

type dealServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDealServiceClient(cc grpc.ClientConnInterface) DealServiceClient {
	return &dealServiceClient{cc}
}

func (c *dealServiceClient) CreateDeal(ctx context.Context, in *CreateDealRequest, opts ...grpc.CallOption) (*DealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DealResponse)
	err := c.cc.Invoke(ctx, DealService_CreateDeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dealServiceClient) GetDeal(ctx context.Context, in *GetDealRequest, opts ...grpc.CallOption) (*DealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DealResponse)
	err := c.cc.Invoke(ctx, DealService_GetDeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dealServiceClient) ListDeals(ctx context.Context, in *ListDealsRequest, opts ...grpc.CallOption) (*ListDealsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDealsResponse)
	err := c.cc.Invoke(ctx, DealService_ListDeals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dealServiceClient) UpdateDeal(ctx context.Context, in *UpdateDealRequest, opts ...grpc.CallOption) (*DealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DealResponse)
	err := c.cc.Invoke(ctx, DealService_UpdateDeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dealServiceClient) AcceptDeal(ctx context.Context, in *AcceptDealRequest, opts ...grpc.CallOption) (*DealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DealResponse)
	err := c.cc.Invoke(ctx, DealService_AcceptDeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DealServiceServer is the server API for DealService service.
// All implementations must embed UnimplementedDealServiceServer
// for forward compatibility.
type DealServiceServer interface {
	// Создать новую сделку.
	CreateDeal(context.Context, *CreateDealRequest) (*DealResponse, error)
	// Получить информацию о конкретной сделке.
	GetDeal(context.Context, *GetDealRequest) (*DealResponse, error)
	// Получить список сделок по фильтру.
	ListDeals(context.Context, *ListDealsRequest) (*ListDealsResponse, error)
	// Обновить сделку (принять, отклонить, отменить, завершить).
	UpdateDeal(context.Context, *UpdateDealRequest) (*DealResponse, error)
	// Принять сделку (покупатель принимает предложение).
	AcceptDeal(context.Context, *AcceptDealRequest) (*DealResponse, error)
	mustEmbedUnimplementedDealServiceServer()
}

// UnimplementedDealServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDealServiceServer struct{}

func (UnimplementedDealServiceServer) CreateDeal(context.Context, *CreateDealRequest) (*DealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeal not implemented")
}
func (UnimplementedDealServiceServer) GetDeal(context.Context, *GetDealRequest) (*DealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeal not implemented")
}
func (UnimplementedDealServiceServer) ListDeals(context.Context, *ListDealsRequest) (*ListDealsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeals not implemented")
}
func (UnimplementedDealServiceServer) UpdateDeal(context.Context, *UpdateDealRequest) (*DealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeal not implemented")
}
func (UnimplementedDealServiceServer) AcceptDeal(context.Context, *AcceptDealRequest) (*DealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptDeal not implemented")
}
func (UnimplementedDealServiceServer) mustEmbedUnimplementedDealServiceServer() {}
func (UnimplementedDealServiceServer) testEmbeddedByValue()                     {}

// UnsafeDealServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DealServiceServer will
// result in compilation errors.
type UnsafeDealServiceServer interface {
	mustEmbedUnimplementedDealServiceServer()
}

func RegisterDealServiceServer(s grpc.ServiceRegistrar, srv DealServiceServer) {
	// If the following call pancis, it indicates UnimplementedDealServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DealService_ServiceDesc, srv)
}

func _DealService_CreateDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealServiceServer).CreateDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DealService_CreateDeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealServiceServer).CreateDeal(ctx, req.(*CreateDealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DealService_GetDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealServiceServer).GetDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DealService_GetDeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealServiceServer).GetDeal(ctx, req.(*GetDealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DealService_ListDeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealServiceServer).ListDeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DealService_ListDeals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealServiceServer).ListDeals(ctx, req.(*ListDealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DealService_UpdateDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealServiceServer).UpdateDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DealService_UpdateDeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealServiceServer).UpdateDeal(ctx, req.(*UpdateDealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DealService_AcceptDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptDealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DealServiceServer).AcceptDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DealService_AcceptDeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DealServiceServer).AcceptDeal(ctx, req.(*AcceptDealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DealService_ServiceDesc is the grpc.ServiceDesc for DealService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DealService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leadexchange.v1.DealService",
	HandlerType: (*DealServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeal",
			Handler:    _DealService_CreateDeal_Handler,
		},
		{
			MethodName: "GetDeal",
			Handler:    _DealService_GetDeal_Handler,
		},
		{
			MethodName: "ListDeals",
			Handler:    _DealService_ListDeals_Handler,
		},
		{
			MethodName: "UpdateDeal",
			Handler:    _DealService_UpdateDeal_Handler,
		},
		{
			MethodName: "AcceptDeal",
			Handler:    _DealService_AcceptDeal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deal.proto",
}
