// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.3
// source: lead.proto

package leadexchangev1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LeadStatus — статус лида.
type LeadStatus int32

const (
	// Не задан (значение по умолчанию, не используется)
	LeadStatus_LEAD_STATUS_UNSPECIFIED LeadStatus = 0
	// Создан, виден только создателю
	LeadStatus_LEAD_STATUS_NEW LeadStatus = 1
	// Опубликован и доступен для покупки
	LeadStatus_LEAD_STATUS_PUBLISHED LeadStatus = 2
	// Куплен покупателем
	LeadStatus_LEAD_STATUS_PURCHASED LeadStatus = 3
	// Удалён администратором
	LeadStatus_LEAD_STATUS_DELETED LeadStatus = 4
)

// Enum value maps for LeadStatus.
var (
	LeadStatus_name = map[int32]string{
		0: "LEAD_STATUS_UNSPECIFIED",
		1: "LEAD_STATUS_NEW",
		2: "LEAD_STATUS_PUBLISHED",
		3: "LEAD_STATUS_PURCHASED",
		4: "LEAD_STATUS_DELETED",
	}
	LeadStatus_value = map[string]int32{
		"LEAD_STATUS_UNSPECIFIED": 0,
		"LEAD_STATUS_NEW":         1,
		"LEAD_STATUS_PUBLISHED":   2,
		"LEAD_STATUS_PURCHASED":   3,
		"LEAD_STATUS_DELETED":     4,
	}
)

func (x LeadStatus) Enum() *LeadStatus {
	p := new(LeadStatus)
	*p = x
	return p
}

func (x LeadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lead_proto_enumTypes[0].Descriptor()
}

func (LeadStatus) Type() protoreflect.EnumType {
	return &file_lead_proto_enumTypes[0]
}

func (x LeadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeadStatus.Descriptor instead.
func (LeadStatus) EnumDescriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{0}
}

// Lead — сущность лида.
type Lead struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID лида
	LeadId      string `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// JSON с предпочтениями ("roomNumber": 3, "price": "5000000")
	Requirement  []byte     `protobuf:"bytes,4,opt,name=requirement,proto3" json:"requirement,omitempty"`
	ContactName  string     `protobuf:"bytes,5,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactPhone string     `protobuf:"bytes,6,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	ContactEmail string     `protobuf:"bytes,7,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	Status       LeadStatus `protobuf:"varint,8,opt,name=status,proto3,enum=leadexchange.v1.LeadStatus" json:"status,omitempty"`
	// текущий владелец
	OwnerUserId string `protobuf:"bytes,9,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	// создатель
	CreatedUserId string `protobuf:"bytes,10,opt,name=created_user_id,json=createdUserId,proto3" json:"created_user_id,omitempty"`
	CreatedAt     string `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lead) Reset() {
	*x = Lead{}
	mi := &file_lead_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lead) ProtoMessage() {}

func (x *Lead) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lead.ProtoReflect.Descriptor instead.
func (*Lead) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{0}
}

func (x *Lead) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *Lead) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lead) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Lead) GetRequirement() []byte {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *Lead) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *Lead) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *Lead) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *Lead) GetStatus() LeadStatus {
	if x != nil {
		return x.Status
	}
	return LeadStatus_LEAD_STATUS_UNSPECIFIED
}

func (x *Lead) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Lead) GetCreatedUserId() string {
	if x != nil {
		return x.CreatedUserId
	}
	return ""
}

func (x *Lead) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Lead) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Requirement   []byte                 `protobuf:"bytes,3,opt,name=requirement,proto3" json:"requirement,omitempty"`
	ContactName   string                 `protobuf:"bytes,4,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactPhone  string                 `protobuf:"bytes,5,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,6,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeadRequest) Reset() {
	*x = CreateLeadRequest{}
	mi := &file_lead_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeadRequest) ProtoMessage() {}

func (x *CreateLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeadRequest.ProtoReflect.Descriptor instead.
func (*CreateLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLeadRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLeadRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateLeadRequest) GetRequirement() []byte {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *CreateLeadRequest) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *CreateLeadRequest) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *CreateLeadRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

type GetLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadId        string                 `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadRequest) Reset() {
	*x = GetLeadRequest{}
	mi := &file_lead_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadRequest) ProtoMessage() {}

func (x *GetLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadRequest.ProtoReflect.Descriptor instead.
func (*GetLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{2}
}

func (x *GetLeadRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

type ListLeadsRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Filter        *ListLeadsRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsRequest) Reset() {
	*x = ListLeadsRequest{}
	mi := &file_lead_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsRequest) ProtoMessage() {}

func (x *ListLeadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsRequest.ProtoReflect.Descriptor instead.
func (*ListLeadsRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{3}
}

func (x *ListLeadsRequest) GetFilter() *ListLeadsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListLeadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leads         []*Lead                `protobuf:"bytes,1,rep,name=leads,proto3" json:"leads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsResponse) Reset() {
	*x = ListLeadsResponse{}
	mi := &file_lead_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsResponse) ProtoMessage() {}

func (x *ListLeadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsResponse.ProtoReflect.Descriptor instead.
func (*ListLeadsResponse) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{4}
}

func (x *ListLeadsResponse) GetLeads() []*Lead {
	if x != nil {
		return x.Leads
	}
	return nil
}

type UpdateLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeadId        string                 `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Requirement   []byte                 `protobuf:"bytes,4,opt,name=requirement,proto3,oneof" json:"requirement,omitempty"`
	Status        *LeadStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=leadexchange.v1.LeadStatus,oneof" json:"status,omitempty"`
	OwnerUserId   *string                `protobuf:"bytes,6,opt,name=owner_user_id,json=ownerUserId,proto3,oneof" json:"owner_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLeadRequest) Reset() {
	*x = UpdateLeadRequest{}
	mi := &file_lead_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeadRequest) ProtoMessage() {}

func (x *UpdateLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeadRequest.ProtoReflect.Descriptor instead.
func (*UpdateLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLeadRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *UpdateLeadRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateLeadRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateLeadRequest) GetRequirement() []byte {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *UpdateLeadRequest) GetStatus() LeadStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return LeadStatus_LEAD_STATUS_UNSPECIFIED
}

func (x *UpdateLeadRequest) GetOwnerUserId() string {
	if x != nil && x.OwnerUserId != nil {
		return *x.OwnerUserId
	}
	return ""
}

type LeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lead          *Lead                  `protobuf:"bytes,1,opt,name=lead,proto3" json:"lead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeadResponse) Reset() {
	*x = LeadResponse{}
	mi := &file_lead_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadResponse) ProtoMessage() {}

func (x *LeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadResponse.ProtoReflect.Descriptor instead.
func (*LeadResponse) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{6}
}

func (x *LeadResponse) GetLead() *Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

type ListLeadsRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *LeadStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=leadexchange.v1.LeadStatus,oneof" json:"status,omitempty"`
	OwnerUserId   *string                `protobuf:"bytes,2,opt,name=owner_user_id,json=ownerUserId,proto3,oneof" json:"owner_user_id,omitempty"`
	CreatedUserId *string                `protobuf:"bytes,3,opt,name=created_user_id,json=createdUserId,proto3,oneof" json:"created_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsRequest_Filter) Reset() {
	*x = ListLeadsRequest_Filter{}
	mi := &file_lead_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsRequest_Filter) ProtoMessage() {}

func (x *ListLeadsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_lead_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListLeadsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_lead_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListLeadsRequest_Filter) GetStatus() LeadStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return LeadStatus_LEAD_STATUS_UNSPECIFIED
}

func (x *ListLeadsRequest_Filter) GetOwnerUserId() string {
	if x != nil && x.OwnerUserId != nil {
		return *x.OwnerUserId
	}
	return ""
}

func (x *ListLeadsRequest_Filter) GetCreatedUserId() string {
	if x != nil && x.CreatedUserId != nil {
		return *x.CreatedUserId
	}
	return ""
}

var File_lead_proto protoreflect.FileDescriptor

const file_lead_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"lead.proto\x12\x0fleadexchange.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xf3\x03\n" +
	"\x04Lead\x12\x17\n" +
	"\alead_id\x18\x01 \x01(\tR\x06leadId\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12 \n" +
	"\vrequirement\x18\x04 \x01(\fR\vrequirement\x12*\n" +
	"\fcontact_name\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\vcontactName\x12?\n" +
	"\rcontact_phone\x18\x06 \x01(\tB\x1a\xfaB\x17r\x152\x13^\\+?[0-9\\s()-]{7,}$R\fcontactPhone\x12/\n" +
	"\rcontact_email\x18\a \x01(\tB\n" +
	"\xfaB\ar\x05\xd0\x01\x01`\x01R\fcontactEmail\x123\n" +
	"\x06status\x18\b \x01(\x0e2\x1b.leadexchange.v1.LeadStatusR\x06status\x12,\n" +
	"\rowner_user_id\x18\t \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\vownerUserId\x120\n" +
	"\x0fcreated_user_id\x18\n" +
	" \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\rcreatedUserId\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\x94\x02\n" +
	"\x11CreateLeadRequest\x12\x1d\n" +
	"\x05title\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12 \n" +
	"\vrequirement\x18\x03 \x01(\fR\vrequirement\x12*\n" +
	"\fcontact_name\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\vcontactName\x12?\n" +
	"\rcontact_phone\x18\x05 \x01(\tB\x1a\xfaB\x17r\x152\x13^\\+?[0-9\\s()-]{7,}$R\fcontactPhone\x12/\n" +
	"\rcontact_email\x18\x06 \x01(\tB\n" +
	"\xfaB\ar\x05\xd0\x01\x01`\x01R\fcontactEmail\"3\n" +
	"\x0eGetLeadRequest\x12!\n" +
	"\alead_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06leadId\"\xa0\x02\n" +
	"\x10ListLeadsRequest\x12@\n" +
	"\x06filter\x18\x01 \x01(\v2(.leadexchange.v1.ListLeadsRequest.FilterR\x06filter\x1a\xc9\x01\n" +
	"\x06Filter\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.leadexchange.v1.LeadStatusH\x00R\x06status\x88\x01\x01\x12'\n" +
	"\rowner_user_id\x18\x02 \x01(\tH\x01R\vownerUserId\x88\x01\x01\x12+\n" +
	"\x0fcreated_user_id\x18\x03 \x01(\tH\x02R\rcreatedUserId\x88\x01\x01B\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_owner_user_idB\x12\n" +
	"\x10_created_user_id\"@\n" +
	"\x11ListLeadsResponse\x12+\n" +
	"\x05leads\x18\x01 \x03(\v2\x15.leadexchange.v1.LeadR\x05leads\"\xc9\x02\n" +
	"\x11UpdateLeadRequest\x12!\n" +
	"\alead_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06leadId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12%\n" +
	"\vrequirement\x18\x04 \x01(\fH\x02R\vrequirement\x88\x01\x01\x128\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.leadexchange.v1.LeadStatusH\x03R\x06status\x88\x01\x01\x12'\n" +
	"\rowner_user_id\x18\x06 \x01(\tH\x04R\vownerUserId\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_requirementB\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_owner_user_id\"9\n" +
	"\fLeadResponse\x12)\n" +
	"\x04lead\x18\x01 \x01(\v2\x15.leadexchange.v1.LeadR\x04lead*\x8d\x01\n" +
	"\n" +
	"LeadStatus\x12\x1b\n" +
	"\x17LEAD_STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLEAD_STATUS_NEW\x10\x01\x12\x19\n" +
	"\x15LEAD_STATUS_PUBLISHED\x10\x02\x12\x19\n" +
	"\x15LEAD_STATUS_PURCHASED\x10\x03\x12\x17\n" +
	"\x13LEAD_STATUS_DELETED\x10\x042\xb4\x03\n" +
	"\vLeadService\x12e\n" +
	"\n" +
	"CreateLead\x12\".leadexchange.v1.CreateLeadRequest\x1a\x1d.leadexchange.v1.LeadResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/leads\x12f\n" +
	"\aGetLead\x12\x1f.leadexchange.v1.GetLeadRequest\x1a\x1d.leadexchange.v1.LeadResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/leads/{lead_id}\x12e\n" +
	"\tListLeads\x12!.leadexchange.v1.ListLeadsRequest\x1a\".leadexchange.v1.ListLeadsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/leads\x12o\n" +
	"\n" +
	"UpdateLead\x12\".leadexchange.v1.UpdateLeadRequest\x1a\x1d.leadexchange.v1.LeadResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*2\x13/v1/leads/{lead_id}B4Z2leadexchange/gen/go/leadexchange/v1;leadexchangev1b\x06proto3"

var (
	file_lead_proto_rawDescOnce sync.Once
	file_lead_proto_rawDescData []byte
)

func file_lead_proto_rawDescGZIP() []byte {
	file_lead_proto_rawDescOnce.Do(func() {
		file_lead_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lead_proto_rawDesc), len(file_lead_proto_rawDesc)))
	})
	return file_lead_proto_rawDescData
}

var file_lead_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lead_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lead_proto_goTypes = []any{
	(LeadStatus)(0),                 // 0: leadexchange.v1.LeadStatus
	(*Lead)(nil),                    // 1: leadexchange.v1.Lead
	(*CreateLeadRequest)(nil),       // 2: leadexchange.v1.CreateLeadRequest
	(*GetLeadRequest)(nil),          // 3: leadexchange.v1.GetLeadRequest
	(*ListLeadsRequest)(nil),        // 4: leadexchange.v1.ListLeadsRequest
	(*ListLeadsResponse)(nil),       // 5: leadexchange.v1.ListLeadsResponse
	(*UpdateLeadRequest)(nil),       // 6: leadexchange.v1.UpdateLeadRequest
	(*LeadResponse)(nil),            // 7: leadexchange.v1.LeadResponse
	(*ListLeadsRequest_Filter)(nil), // 8: leadexchange.v1.ListLeadsRequest.Filter
}
var file_lead_proto_depIdxs = []int32{
	0,  // 0: leadexchange.v1.Lead.status:type_name -> leadexchange.v1.LeadStatus
	8,  // 1: leadexchange.v1.ListLeadsRequest.filter:type_name -> leadexchange.v1.ListLeadsRequest.Filter
	1,  // 2: leadexchange.v1.ListLeadsResponse.leads:type_name -> leadexchange.v1.Lead
	0,  // 3: leadexchange.v1.UpdateLeadRequest.status:type_name -> leadexchange.v1.LeadStatus
	1,  // 4: leadexchange.v1.LeadResponse.lead:type_name -> leadexchange.v1.Lead
	0,  // 5: leadexchange.v1.ListLeadsRequest.Filter.status:type_name -> leadexchange.v1.LeadStatus
	2,  // 6: leadexchange.v1.LeadService.CreateLead:input_type -> leadexchange.v1.CreateLeadRequest
	3,  // 7: leadexchange.v1.LeadService.GetLead:input_type -> leadexchange.v1.GetLeadRequest
	4,  // 8: leadexchange.v1.LeadService.ListLeads:input_type -> leadexchange.v1.ListLeadsRequest
	6,  // 9: leadexchange.v1.LeadService.UpdateLead:input_type -> leadexchange.v1.UpdateLeadRequest
	7,  // 10: leadexchange.v1.LeadService.CreateLead:output_type -> leadexchange.v1.LeadResponse
	7,  // 11: leadexchange.v1.LeadService.GetLead:output_type -> leadexchange.v1.LeadResponse
	5,  // 12: leadexchange.v1.LeadService.ListLeads:output_type -> leadexchange.v1.ListLeadsResponse
	7,  // 13: leadexchange.v1.LeadService.UpdateLead:output_type -> leadexchange.v1.LeadResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_lead_proto_init() }
func file_lead_proto_init() {
	if File_lead_proto != nil {
		return
	}
	file_lead_proto_msgTypes[5].OneofWrappers = []any{}
	file_lead_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lead_proto_rawDesc), len(file_lead_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lead_proto_goTypes,
		DependencyIndexes: file_lead_proto_depIdxs,
		EnumInfos:         file_lead_proto_enumTypes,
		MessageInfos:      file_lead_proto_msgTypes,
	}.Build()
	File_lead_proto = out.File
	file_lead_proto_goTypes = nil
	file_lead_proto_depIdxs = nil
}
