// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.3
// source: property.proto

package leadexchangev1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PropertyType — тип недвижимости.
type PropertyType int32

const (
	// Не задан (значение по умолчанию, не используется)
	PropertyType_PROPERTY_TYPE_UNSPECIFIED PropertyType = 0
	// Квартира
	PropertyType_PROPERTY_TYPE_APARTMENT PropertyType = 1
	// Дом
	PropertyType_PROPERTY_TYPE_HOUSE PropertyType = 2
	// Коммерческая недвижимость
	PropertyType_PROPERTY_TYPE_COMMERCIAL PropertyType = 3
	// Земельный участок
	PropertyType_PROPERTY_TYPE_LAND PropertyType = 4
)

// Enum value maps for PropertyType.
var (
	PropertyType_name = map[int32]string{
		0: "PROPERTY_TYPE_UNSPECIFIED",
		1: "PROPERTY_TYPE_APARTMENT",
		2: "PROPERTY_TYPE_HOUSE",
		3: "PROPERTY_TYPE_COMMERCIAL",
		4: "PROPERTY_TYPE_LAND",
	}
	PropertyType_value = map[string]int32{
		"PROPERTY_TYPE_UNSPECIFIED": 0,
		"PROPERTY_TYPE_APARTMENT":   1,
		"PROPERTY_TYPE_HOUSE":       2,
		"PROPERTY_TYPE_COMMERCIAL":  3,
		"PROPERTY_TYPE_LAND":        4,
	}
)

func (x PropertyType) Enum() *PropertyType {
	p := new(PropertyType)
	*p = x
	return p
}

func (x PropertyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropertyType) Descriptor() protoreflect.EnumDescriptor {
	return file_property_proto_enumTypes[0].Descriptor()
}

func (PropertyType) Type() protoreflect.EnumType {
	return &file_property_proto_enumTypes[0]
}

func (x PropertyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropertyType.Descriptor instead.
func (PropertyType) EnumDescriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{0}
}

// PropertyStatus — статус объекта недвижимости.
type PropertyStatus int32

const (
	// Не задан (значение по умолчанию, не используется)
	PropertyStatus_PROPERTY_STATUS_UNSPECIFIED PropertyStatus = 0
	// Создан, виден только создателю
	PropertyStatus_PROPERTY_STATUS_NEW PropertyStatus = 1
	// Опубликован и доступен для просмотра
	PropertyStatus_PROPERTY_STATUS_PUBLISHED PropertyStatus = 2
	// Продан
	PropertyStatus_PROPERTY_STATUS_SOLD PropertyStatus = 3
	// Удалён администратором
	PropertyStatus_PROPERTY_STATUS_DELETED PropertyStatus = 4
)

// Enum value maps for PropertyStatus.
var (
	PropertyStatus_name = map[int32]string{
		0: "PROPERTY_STATUS_UNSPECIFIED",
		1: "PROPERTY_STATUS_NEW",
		2: "PROPERTY_STATUS_PUBLISHED",
		3: "PROPERTY_STATUS_SOLD",
		4: "PROPERTY_STATUS_DELETED",
	}
	PropertyStatus_value = map[string]int32{
		"PROPERTY_STATUS_UNSPECIFIED": 0,
		"PROPERTY_STATUS_NEW":         1,
		"PROPERTY_STATUS_PUBLISHED":   2,
		"PROPERTY_STATUS_SOLD":        3,
		"PROPERTY_STATUS_DELETED":     4,
	}
)

func (x PropertyStatus) Enum() *PropertyStatus {
	p := new(PropertyStatus)
	*p = x
	return p
}

func (x PropertyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropertyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_property_proto_enumTypes[1].Descriptor()
}

func (PropertyStatus) Type() protoreflect.EnumType {
	return &file_property_proto_enumTypes[1]
}

func (x PropertyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropertyStatus.Descriptor instead.
func (PropertyStatus) EnumDescriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{1}
}

// Property — сущность объекта недвижимости.
type Property struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID объекта недвижимости
	PropertyId   string       `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	Title        string       `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description  string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Address      string       `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PropertyType PropertyType `protobuf:"varint,5,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType" json:"property_type,omitempty"`
	// Площадь в квадратных метрах
	Area *float64 `protobuf:"fixed64,6,opt,name=area,proto3,oneof" json:"area,omitempty"`
	// Цена в рублях
	Price *int64 `protobuf:"varint,7,opt,name=price,proto3,oneof" json:"price,omitempty"`
	// Количество комнат
	Rooms  *int32         `protobuf:"varint,8,opt,name=rooms,proto3,oneof" json:"rooms,omitempty"`
	Status PropertyStatus `protobuf:"varint,9,opt,name=status,proto3,enum=leadexchange.v1.PropertyStatus" json:"status,omitempty"`
	// текущий владелец
	OwnerUserId string `protobuf:"bytes,10,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	// создатель
	CreatedUserId string `protobuf:"bytes,11,opt,name=created_user_id,json=createdUserId,proto3" json:"created_user_id,omitempty"`
	CreatedAt     string `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_property_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *Property) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Property) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Property) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Property) GetPropertyType() PropertyType {
	if x != nil {
		return x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

func (x *Property) GetArea() float64 {
	if x != nil && x.Area != nil {
		return *x.Area
	}
	return 0
}

func (x *Property) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *Property) GetRooms() int32 {
	if x != nil && x.Rooms != nil {
		return *x.Rooms
	}
	return 0
}

func (x *Property) GetStatus() PropertyStatus {
	if x != nil {
		return x.Status
	}
	return PropertyStatus_PROPERTY_STATUS_UNSPECIFIED
}

func (x *Property) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Property) GetCreatedUserId() string {
	if x != nil {
		return x.CreatedUserId
	}
	return ""
}

func (x *Property) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Property) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreatePropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PropertyType  PropertyType           `protobuf:"varint,4,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType" json:"property_type,omitempty"`
	Area          *float64               `protobuf:"fixed64,5,opt,name=area,proto3,oneof" json:"area,omitempty"`
	Price         *int64                 `protobuf:"varint,6,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Rooms         *int32                 `protobuf:"varint,7,opt,name=rooms,proto3,oneof" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePropertyRequest) Reset() {
	*x = CreatePropertyRequest{}
	mi := &file_property_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePropertyRequest) ProtoMessage() {}

func (x *CreatePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePropertyRequest.ProtoReflect.Descriptor instead.
func (*CreatePropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePropertyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePropertyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePropertyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreatePropertyRequest) GetPropertyType() PropertyType {
	if x != nil {
		return x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

func (x *CreatePropertyRequest) GetArea() float64 {
	if x != nil && x.Area != nil {
		return *x.Area
	}
	return 0
}

func (x *CreatePropertyRequest) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *CreatePropertyRequest) GetRooms() int32 {
	if x != nil && x.Rooms != nil {
		return *x.Rooms
	}
	return 0
}

type GetPropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertyRequest) Reset() {
	*x = GetPropertyRequest{}
	mi := &file_property_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertyRequest) ProtoMessage() {}

func (x *GetPropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertyRequest.ProtoReflect.Descriptor instead.
func (*GetPropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{2}
}

func (x *GetPropertyRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

type ListPropertiesRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Filter        *ListPropertiesRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertiesRequest) Reset() {
	*x = ListPropertiesRequest{}
	mi := &file_property_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertiesRequest) ProtoMessage() {}

func (x *ListPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertiesRequest.ProtoReflect.Descriptor instead.
func (*ListPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{3}
}

func (x *ListPropertiesRequest) GetFilter() *ListPropertiesRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListPropertiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    []*Property            `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertiesResponse) Reset() {
	*x = ListPropertiesResponse{}
	mi := &file_property_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertiesResponse) ProtoMessage() {}

func (x *ListPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertiesResponse.ProtoReflect.Descriptor instead.
func (*ListPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{4}
}

func (x *ListPropertiesResponse) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

type UpdatePropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropertyId    string                 `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Address       *string                `protobuf:"bytes,4,opt,name=address,proto3,oneof" json:"address,omitempty"`
	PropertyType  *PropertyType          `protobuf:"varint,5,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType,oneof" json:"property_type,omitempty"`
	Area          *float64               `protobuf:"fixed64,6,opt,name=area,proto3,oneof" json:"area,omitempty"`
	Price         *int64                 `protobuf:"varint,7,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Rooms         *int32                 `protobuf:"varint,8,opt,name=rooms,proto3,oneof" json:"rooms,omitempty"`
	Status        *PropertyStatus        `protobuf:"varint,9,opt,name=status,proto3,enum=leadexchange.v1.PropertyStatus,oneof" json:"status,omitempty"`
	OwnerUserId   *string                `protobuf:"bytes,10,opt,name=owner_user_id,json=ownerUserId,proto3,oneof" json:"owner_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePropertyRequest) Reset() {
	*x = UpdatePropertyRequest{}
	mi := &file_property_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePropertyRequest) ProtoMessage() {}

func (x *UpdatePropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePropertyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePropertyRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePropertyRequest) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *UpdatePropertyRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdatePropertyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdatePropertyRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *UpdatePropertyRequest) GetPropertyType() PropertyType {
	if x != nil && x.PropertyType != nil {
		return *x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

func (x *UpdatePropertyRequest) GetArea() float64 {
	if x != nil && x.Area != nil {
		return *x.Area
	}
	return 0
}

func (x *UpdatePropertyRequest) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdatePropertyRequest) GetRooms() int32 {
	if x != nil && x.Rooms != nil {
		return *x.Rooms
	}
	return 0
}

func (x *UpdatePropertyRequest) GetStatus() PropertyStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PropertyStatus_PROPERTY_STATUS_UNSPECIFIED
}

func (x *UpdatePropertyRequest) GetOwnerUserId() string {
	if x != nil && x.OwnerUserId != nil {
		return *x.OwnerUserId
	}
	return ""
}

type PropertyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Property      *Property              `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyResponse) Reset() {
	*x = PropertyResponse{}
	mi := &file_property_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyResponse) ProtoMessage() {}

func (x *PropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyResponse.ProtoReflect.Descriptor instead.
func (*PropertyResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{6}
}

func (x *PropertyResponse) GetProperty() *Property {
	if x != nil {
		return x.Property
	}
	return nil
}

// MatchPropertiesRequest — запрос на поиск подходящих объектов для лида.
type MatchPropertiesRequest struct {
	state  protoimpl.MessageState         `protogen:"open.v1"`
	LeadId string                         `protobuf:"bytes,1,opt,name=lead_id,json=leadId,proto3" json:"lead_id,omitempty"`
	Filter *MatchPropertiesRequest_Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	// Лимит результатов (по умолчанию 10)
	Limit         *int32 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchPropertiesRequest) Reset() {
	*x = MatchPropertiesRequest{}
	mi := &file_property_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPropertiesRequest) ProtoMessage() {}

func (x *MatchPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPropertiesRequest.ProtoReflect.Descriptor instead.
func (*MatchPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{7}
}

func (x *MatchPropertiesRequest) GetLeadId() string {
	if x != nil {
		return x.LeadId
	}
	return ""
}

func (x *MatchPropertiesRequest) GetFilter() *MatchPropertiesRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *MatchPropertiesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

// MatchedProperty — объект недвижимости с коэффициентом схожести.
type MatchedProperty struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Property *Property              `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	// Коэффициент схожести (0-1, где 1 - полное совпадение)
	Similarity    float64 `protobuf:"fixed64,2,opt,name=similarity,proto3" json:"similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchedProperty) Reset() {
	*x = MatchedProperty{}
	mi := &file_property_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchedProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchedProperty) ProtoMessage() {}

func (x *MatchedProperty) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchedProperty.ProtoReflect.Descriptor instead.
func (*MatchedProperty) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{8}
}

func (x *MatchedProperty) GetProperty() *Property {
	if x != nil {
		return x.Property
	}
	return nil
}

func (x *MatchedProperty) GetSimilarity() float64 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

// MatchPropertiesResponse — ответ с подходящими объектами.
type MatchPropertiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*MatchedProperty     `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchPropertiesResponse) Reset() {
	*x = MatchPropertiesResponse{}
	mi := &file_property_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPropertiesResponse) ProtoMessage() {}

func (x *MatchPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPropertiesResponse.ProtoReflect.Descriptor instead.
func (*MatchPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{9}
}

func (x *MatchPropertiesResponse) GetMatches() []*MatchedProperty {
	if x != nil {
		return x.Matches
	}
	return nil
}

type ListPropertiesRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *PropertyStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=leadexchange.v1.PropertyStatus,oneof" json:"status,omitempty"`
	OwnerUserId   *string                `protobuf:"bytes,2,opt,name=owner_user_id,json=ownerUserId,proto3,oneof" json:"owner_user_id,omitempty"`
	CreatedUserId *string                `protobuf:"bytes,3,opt,name=created_user_id,json=createdUserId,proto3,oneof" json:"created_user_id,omitempty"`
	PropertyType  *PropertyType          `protobuf:"varint,4,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType,oneof" json:"property_type,omitempty"`
	MinRooms      *int32                 `protobuf:"varint,5,opt,name=min_rooms,json=minRooms,proto3,oneof" json:"min_rooms,omitempty"`
	MaxRooms      *int32                 `protobuf:"varint,6,opt,name=max_rooms,json=maxRooms,proto3,oneof" json:"max_rooms,omitempty"`
	MinPrice      *int64                 `protobuf:"varint,7,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *int64                 `protobuf:"varint,8,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPropertiesRequest_Filter) Reset() {
	*x = ListPropertiesRequest_Filter{}
	mi := &file_property_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPropertiesRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPropertiesRequest_Filter) ProtoMessage() {}

func (x *ListPropertiesRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPropertiesRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListPropertiesRequest_Filter) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListPropertiesRequest_Filter) GetStatus() PropertyStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PropertyStatus_PROPERTY_STATUS_UNSPECIFIED
}

func (x *ListPropertiesRequest_Filter) GetOwnerUserId() string {
	if x != nil && x.OwnerUserId != nil {
		return *x.OwnerUserId
	}
	return ""
}

func (x *ListPropertiesRequest_Filter) GetCreatedUserId() string {
	if x != nil && x.CreatedUserId != nil {
		return *x.CreatedUserId
	}
	return ""
}

func (x *ListPropertiesRequest_Filter) GetPropertyType() PropertyType {
	if x != nil && x.PropertyType != nil {
		return *x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

func (x *ListPropertiesRequest_Filter) GetMinRooms() int32 {
	if x != nil && x.MinRooms != nil {
		return *x.MinRooms
	}
	return 0
}

func (x *ListPropertiesRequest_Filter) GetMaxRooms() int32 {
	if x != nil && x.MaxRooms != nil {
		return *x.MaxRooms
	}
	return 0
}

func (x *ListPropertiesRequest_Filter) GetMinPrice() int64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *ListPropertiesRequest_Filter) GetMaxPrice() int64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

type MatchPropertiesRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *PropertyStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=leadexchange.v1.PropertyStatus,oneof" json:"status,omitempty"`
	PropertyType  *PropertyType          `protobuf:"varint,2,opt,name=property_type,json=propertyType,proto3,enum=leadexchange.v1.PropertyType,oneof" json:"property_type,omitempty"`
	MinRooms      *int32                 `protobuf:"varint,3,opt,name=min_rooms,json=minRooms,proto3,oneof" json:"min_rooms,omitempty"`
	MaxRooms      *int32                 `protobuf:"varint,4,opt,name=max_rooms,json=maxRooms,proto3,oneof" json:"max_rooms,omitempty"`
	MinPrice      *int64                 `protobuf:"varint,5,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *int64                 `protobuf:"varint,6,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchPropertiesRequest_Filter) Reset() {
	*x = MatchPropertiesRequest_Filter{}
	mi := &file_property_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchPropertiesRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchPropertiesRequest_Filter) ProtoMessage() {}

func (x *MatchPropertiesRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_property_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchPropertiesRequest_Filter.ProtoReflect.Descriptor instead.
func (*MatchPropertiesRequest_Filter) Descriptor() ([]byte, []int) {
	return file_property_proto_rawDescGZIP(), []int{7, 0}
}

func (x *MatchPropertiesRequest_Filter) GetStatus() PropertyStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PropertyStatus_PROPERTY_STATUS_UNSPECIFIED
}

func (x *MatchPropertiesRequest_Filter) GetPropertyType() PropertyType {
	if x != nil && x.PropertyType != nil {
		return *x.PropertyType
	}
	return PropertyType_PROPERTY_TYPE_UNSPECIFIED
}

func (x *MatchPropertiesRequest_Filter) GetMinRooms() int32 {
	if x != nil && x.MinRooms != nil {
		return *x.MinRooms
	}
	return 0
}

func (x *MatchPropertiesRequest_Filter) GetMaxRooms() int32 {
	if x != nil && x.MaxRooms != nil {
		return *x.MaxRooms
	}
	return 0
}

func (x *MatchPropertiesRequest_Filter) GetMinPrice() int64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *MatchPropertiesRequest_Filter) GetMaxPrice() int64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

var File_property_proto protoreflect.FileDescriptor

const file_property_proto_rawDesc = "" +
	"\n" +
	"\x0eproperty.proto\x12\x0fleadexchange.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\x96\x04\n" +
	"\bProperty\x12\x1f\n" +
	"\vproperty_id\x18\x01 \x01(\tR\n" +
	"propertyId\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\aaddress\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x05R\aaddress\x12B\n" +
	"\rproperty_type\x18\x05 \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeR\fpropertyType\x12\x17\n" +
	"\x04area\x18\x06 \x01(\x01H\x00R\x04area\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\a \x01(\x03H\x01R\x05price\x88\x01\x01\x12\x19\n" +
	"\x05rooms\x18\b \x01(\x05H\x02R\x05rooms\x88\x01\x01\x127\n" +
	"\x06status\x18\t \x01(\x0e2\x1f.leadexchange.v1.PropertyStatusR\x06status\x12,\n" +
	"\rowner_user_id\x18\n" +
	" \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\vownerUserId\x120\n" +
	"\x0fcreated_user_id\x18\v \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\rcreatedUserId\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAtB\a\n" +
	"\x05_areaB\b\n" +
	"\x06_priceB\b\n" +
	"\x06_rooms\"\xb5\x02\n" +
	"\x15CreatePropertyRequest\x12\x1d\n" +
	"\x05title\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\aaddress\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x05R\aaddress\x12L\n" +
	"\rproperty_type\x18\x04 \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\fpropertyType\x12\x17\n" +
	"\x04area\x18\x05 \x01(\x01H\x00R\x04area\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x06 \x01(\x03H\x01R\x05price\x88\x01\x01\x12\x19\n" +
	"\x05rooms\x18\a \x01(\x05H\x02R\x05rooms\x88\x01\x01B\a\n" +
	"\x05_areaB\b\n" +
	"\x06_priceB\b\n" +
	"\x06_rooms\"?\n" +
	"\x12GetPropertyRequest\x12)\n" +
	"\vproperty_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"propertyId\"\xc9\x04\n" +
	"\x15ListPropertiesRequest\x12E\n" +
	"\x06filter\x18\x01 \x01(\v2-.leadexchange.v1.ListPropertiesRequest.FilterR\x06filter\x1a\xe8\x03\n" +
	"\x06Filter\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.leadexchange.v1.PropertyStatusH\x00R\x06status\x88\x01\x01\x12'\n" +
	"\rowner_user_id\x18\x02 \x01(\tH\x01R\vownerUserId\x88\x01\x01\x12+\n" +
	"\x0fcreated_user_id\x18\x03 \x01(\tH\x02R\rcreatedUserId\x88\x01\x01\x12G\n" +
	"\rproperty_type\x18\x04 \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeH\x03R\fpropertyType\x88\x01\x01\x12 \n" +
	"\tmin_rooms\x18\x05 \x01(\x05H\x04R\bminRooms\x88\x01\x01\x12 \n" +
	"\tmax_rooms\x18\x06 \x01(\x05H\x05R\bmaxRooms\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\a \x01(\x03H\x06R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\b \x01(\x03H\aR\bmaxPrice\x88\x01\x01B\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_owner_user_idB\x12\n" +
	"\x10_created_user_idB\x10\n" +
	"\x0e_property_typeB\f\n" +
	"\n" +
	"_min_roomsB\f\n" +
	"\n" +
	"_max_roomsB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_price\"S\n" +
	"\x16ListPropertiesResponse\x129\n" +
	"\n" +
	"properties\x18\x01 \x03(\v2\x19.leadexchange.v1.PropertyR\n" +
	"properties\"\x94\x04\n" +
	"\x15UpdatePropertyRequest\x12)\n" +
	"\vproperty_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"propertyId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x04 \x01(\tH\x02R\aaddress\x88\x01\x01\x12G\n" +
	"\rproperty_type\x18\x05 \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeH\x03R\fpropertyType\x88\x01\x01\x12\x17\n" +
	"\x04area\x18\x06 \x01(\x01H\x04R\x04area\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\a \x01(\x03H\x05R\x05price\x88\x01\x01\x12\x19\n" +
	"\x05rooms\x18\b \x01(\x05H\x06R\x05rooms\x88\x01\x01\x12<\n" +
	"\x06status\x18\t \x01(\x0e2\x1f.leadexchange.v1.PropertyStatusH\aR\x06status\x88\x01\x01\x12'\n" +
	"\rowner_user_id\x18\n" +
	" \x01(\tH\bR\vownerUserId\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_addressB\x10\n" +
	"\x0e_property_typeB\a\n" +
	"\x05_areaB\b\n" +
	"\x06_priceB\b\n" +
	"\x06_roomsB\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_owner_user_id\"I\n" +
	"\x10PropertyResponse\x125\n" +
	"\bproperty\x18\x01 \x01(\v2\x19.leadexchange.v1.PropertyR\bproperty\"\x97\x04\n" +
	"\x16MatchPropertiesRequest\x12!\n" +
	"\alead_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06leadId\x12F\n" +
	"\x06filter\x18\x02 \x01(\v2..leadexchange.v1.MatchPropertiesRequest.FilterR\x06filter\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x00R\x05limit\x88\x01\x01\x1a\xec\x02\n" +
	"\x06Filter\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.leadexchange.v1.PropertyStatusH\x00R\x06status\x88\x01\x01\x12G\n" +
	"\rproperty_type\x18\x02 \x01(\x0e2\x1d.leadexchange.v1.PropertyTypeH\x01R\fpropertyType\x88\x01\x01\x12 \n" +
	"\tmin_rooms\x18\x03 \x01(\x05H\x02R\bminRooms\x88\x01\x01\x12 \n" +
	"\tmax_rooms\x18\x04 \x01(\x05H\x03R\bmaxRooms\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\x05 \x01(\x03H\x04R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\x06 \x01(\x03H\x05R\bmaxPrice\x88\x01\x01B\t\n" +
	"\a_statusB\x10\n" +
	"\x0e_property_typeB\f\n" +
	"\n" +
	"_min_roomsB\f\n" +
	"\n" +
	"_max_roomsB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_priceB\b\n" +
	"\x06_limit\"h\n" +
	"\x0fMatchedProperty\x125\n" +
	"\bproperty\x18\x01 \x01(\v2\x19.leadexchange.v1.PropertyR\bproperty\x12\x1e\n" +
	"\n" +
	"similarity\x18\x02 \x01(\x01R\n" +
	"similarity\"U\n" +
	"\x17MatchPropertiesResponse\x12:\n" +
	"\amatches\x18\x01 \x03(\v2 .leadexchange.v1.MatchedPropertyR\amatches*\x99\x01\n" +
	"\fPropertyType\x12\x1d\n" +
	"\x19PROPERTY_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PROPERTY_TYPE_APARTMENT\x10\x01\x12\x17\n" +
	"\x13PROPERTY_TYPE_HOUSE\x10\x02\x12\x1c\n" +
	"\x18PROPERTY_TYPE_COMMERCIAL\x10\x03\x12\x16\n" +
	"\x12PROPERTY_TYPE_LAND\x10\x04*\xa0\x01\n" +
	"\x0ePropertyStatus\x12\x1f\n" +
	"\x1bPROPERTY_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PROPERTY_STATUS_NEW\x10\x01\x12\x1d\n" +
	"\x19PROPERTY_STATUS_PUBLISHED\x10\x02\x12\x18\n" +
	"\x14PROPERTY_STATUS_SOLD\x10\x03\x12\x1b\n" +
	"\x17PROPERTY_STATUS_DELETED\x10\x042\x90\x05\n" +
	"\x0fPropertyService\x12v\n" +
	"\x0eCreateProperty\x12&.leadexchange.v1.CreatePropertyRequest\x1a!.leadexchange.v1.PropertyResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/properties\x12{\n" +
	"\vGetProperty\x12#.leadexchange.v1.GetPropertyRequest\x1a!.leadexchange.v1.PropertyResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/properties/{property_id}\x12y\n" +
	"\x0eListProperties\x12&.leadexchange.v1.ListPropertiesRequest\x1a'.leadexchange.v1.ListPropertiesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/properties\x12\x84\x01\n" +
	"\x0eUpdateProperty\x12&.leadexchange.v1.UpdatePropertyRequest\x1a!.leadexchange.v1.PropertyResponse\"'\x82\xd3\xe4\x93\x02!:\x01*2\x1c/v1/properties/{property_id}\x12\x85\x01\n" +
	"\x0fMatchProperties\x12'.leadexchange.v1.MatchPropertiesRequest\x1a(.leadexchange.v1.MatchPropertiesResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/properties/matchB4Z2leadexchange/gen/go/leadexchange/v1;leadexchangev1b\x06proto3"

var (
	file_property_proto_rawDescOnce sync.Once
	file_property_proto_rawDescData []byte
)

func file_property_proto_rawDescGZIP() []byte {
	file_property_proto_rawDescOnce.Do(func() {
		file_property_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_property_proto_rawDesc), len(file_property_proto_rawDesc)))
	})
	return file_property_proto_rawDescData
}

var file_property_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_property_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_property_proto_goTypes = []any{
	(PropertyType)(0),                     // 0: leadexchange.v1.PropertyType
	(PropertyStatus)(0),                   // 1: leadexchange.v1.PropertyStatus
	(*Property)(nil),                      // 2: leadexchange.v1.Property
	(*CreatePropertyRequest)(nil),         // 3: leadexchange.v1.CreatePropertyRequest
	(*GetPropertyRequest)(nil),            // 4: leadexchange.v1.GetPropertyRequest
	(*ListPropertiesRequest)(nil),         // 5: leadexchange.v1.ListPropertiesRequest
	(*ListPropertiesResponse)(nil),        // 6: leadexchange.v1.ListPropertiesResponse
	(*UpdatePropertyRequest)(nil),         // 7: leadexchange.v1.UpdatePropertyRequest
	(*PropertyResponse)(nil),              // 8: leadexchange.v1.PropertyResponse
	(*MatchPropertiesRequest)(nil),        // 9: leadexchange.v1.MatchPropertiesRequest
	(*MatchedProperty)(nil),               // 10: leadexchange.v1.MatchedProperty
	(*MatchPropertiesResponse)(nil),       // 11: leadexchange.v1.MatchPropertiesResponse
	(*ListPropertiesRequest_Filter)(nil),  // 12: leadexchange.v1.ListPropertiesRequest.Filter
	(*MatchPropertiesRequest_Filter)(nil), // 13: leadexchange.v1.MatchPropertiesRequest.Filter
}
var file_property_proto_depIdxs = []int32{
	0,  // 0: leadexchange.v1.Property.property_type:type_name -> leadexchange.v1.PropertyType
	1,  // 1: leadexchange.v1.Property.status:type_name -> leadexchange.v1.PropertyStatus
	0,  // 2: leadexchange.v1.CreatePropertyRequest.property_type:type_name -> leadexchange.v1.PropertyType
	12, // 3: leadexchange.v1.ListPropertiesRequest.filter:type_name -> leadexchange.v1.ListPropertiesRequest.Filter
	2,  // 4: leadexchange.v1.ListPropertiesResponse.properties:type_name -> leadexchange.v1.Property
	0,  // 5: leadexchange.v1.UpdatePropertyRequest.property_type:type_name -> leadexchange.v1.PropertyType
	1,  // 6: leadexchange.v1.UpdatePropertyRequest.status:type_name -> leadexchange.v1.PropertyStatus
	2,  // 7: leadexchange.v1.PropertyResponse.property:type_name -> leadexchange.v1.Property
	13, // 8: leadexchange.v1.MatchPropertiesRequest.filter:type_name -> leadexchange.v1.MatchPropertiesRequest.Filter
	2,  // 9: leadexchange.v1.MatchedProperty.property:type_name -> leadexchange.v1.Property
	10, // 10: leadexchange.v1.MatchPropertiesResponse.matches:type_name -> leadexchange.v1.MatchedProperty
	1,  // 11: leadexchange.v1.ListPropertiesRequest.Filter.status:type_name -> leadexchange.v1.PropertyStatus
	0,  // 12: leadexchange.v1.ListPropertiesRequest.Filter.property_type:type_name -> leadexchange.v1.PropertyType
	1,  // 13: leadexchange.v1.MatchPropertiesRequest.Filter.status:type_name -> leadexchange.v1.PropertyStatus
	0,  // 14: leadexchange.v1.MatchPropertiesRequest.Filter.property_type:type_name -> leadexchange.v1.PropertyType
	3,  // 15: leadexchange.v1.PropertyService.CreateProperty:input_type -> leadexchange.v1.CreatePropertyRequest
	4,  // 16: leadexchange.v1.PropertyService.GetProperty:input_type -> leadexchange.v1.GetPropertyRequest
	5,  // 17: leadexchange.v1.PropertyService.ListProperties:input_type -> leadexchange.v1.ListPropertiesRequest
	7,  // 18: leadexchange.v1.PropertyService.UpdateProperty:input_type -> leadexchange.v1.UpdatePropertyRequest
	9,  // 19: leadexchange.v1.PropertyService.MatchProperties:input_type -> leadexchange.v1.MatchPropertiesRequest
	8,  // 20: leadexchange.v1.PropertyService.CreateProperty:output_type -> leadexchange.v1.PropertyResponse
	8,  // 21: leadexchange.v1.PropertyService.GetProperty:output_type -> leadexchange.v1.PropertyResponse
	6,  // 22: leadexchange.v1.PropertyService.ListProperties:output_type -> leadexchange.v1.ListPropertiesResponse
	8,  // 23: leadexchange.v1.PropertyService.UpdateProperty:output_type -> leadexchange.v1.PropertyResponse
	11, // 24: leadexchange.v1.PropertyService.MatchProperties:output_type -> leadexchange.v1.MatchPropertiesResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_property_proto_init() }
func file_property_proto_init() {
	if File_property_proto != nil {
		return
	}
	file_property_proto_msgTypes[0].OneofWrappers = []any{}
	file_property_proto_msgTypes[1].OneofWrappers = []any{}
	file_property_proto_msgTypes[5].OneofWrappers = []any{}
	file_property_proto_msgTypes[7].OneofWrappers = []any{}
	file_property_proto_msgTypes[10].OneofWrappers = []any{}
	file_property_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_property_proto_rawDesc), len(file_property_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_property_proto_goTypes,
		DependencyIndexes: file_property_proto_depIdxs,
		EnumInfos:         file_property_proto_enumTypes,
		MessageInfos:      file_property_proto_msgTypes,
	}.Build()
	File_property_proto = out.File
	file_property_proto_goTypes = nil
	file_property_proto_depIdxs = nil
}
