// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: property.proto

package leadexchangev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _property_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Property with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Property) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Property with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PropertyMultiError, or nil
// if none found.
func (m *Property) ValidateAll() error {
	return m.validate(true)
}

func (m *Property) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PropertyId

	if utf8.RuneCountInString(m.GetTitle()) < 3 {
		err := PropertyValidationError{
			field:  "Title",
			reason: "value length must be at least 3 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Description

	if utf8.RuneCountInString(m.GetAddress()) < 5 {
		err := PropertyValidationError{
			field:  "Address",
			reason: "value length must be at least 5 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for PropertyType

	// no validation rules for Status

	if err := m._validateUuid(m.GetOwnerUserId()); err != nil {
		err = PropertyValidationError{
			field:  "OwnerUserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetCreatedUserId()); err != nil {
		err = PropertyValidationError{
			field:  "CreatedUserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if m.Area != nil {
		// no validation rules for Area
	}

	if m.Price != nil {
		// no validation rules for Price
	}

	if m.Rooms != nil {
		// no validation rules for Rooms
	}

	if len(errors) > 0 {
		return PropertyMultiError(errors)
	}

	return nil
}

func (m *Property) _validateUuid(uuid string) error {
	if matched := _property_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PropertyMultiError is an error wrapping multiple validation errors returned
// by Property.ValidateAll() if the designated constraints aren't met.
type PropertyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PropertyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PropertyMultiError) AllErrors() []error { return m }

// PropertyValidationError is the validation error returned by
// Property.Validate if the designated constraints aren't met.
type PropertyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PropertyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PropertyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PropertyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PropertyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PropertyValidationError) ErrorName() string { return "PropertyValidationError" }

// Error satisfies the builtin error interface
func (e PropertyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProperty.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PropertyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PropertyValidationError{}

// Validate checks the field values on CreatePropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreatePropertyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreatePropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreatePropertyRequestMultiError, or nil if none found.
func (m *CreatePropertyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreatePropertyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTitle()) < 3 {
		err := CreatePropertyRequestValidationError{
			field:  "Title",
			reason: "value length must be at least 3 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Description

	if utf8.RuneCountInString(m.GetAddress()) < 5 {
		err := CreatePropertyRequestValidationError{
			field:  "Address",
			reason: "value length must be at least 5 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := PropertyType_name[int32(m.GetPropertyType())]; !ok {
		err := CreatePropertyRequestValidationError{
			field:  "PropertyType",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Area != nil {
		// no validation rules for Area
	}

	if m.Price != nil {
		// no validation rules for Price
	}

	if m.Rooms != nil {
		// no validation rules for Rooms
	}

	if len(errors) > 0 {
		return CreatePropertyRequestMultiError(errors)
	}

	return nil
}

// CreatePropertyRequestMultiError is an error wrapping multiple validation
// errors returned by CreatePropertyRequest.ValidateAll() if the designated
// constraints aren't met.
type CreatePropertyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreatePropertyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreatePropertyRequestMultiError) AllErrors() []error { return m }

// CreatePropertyRequestValidationError is the validation error returned by
// CreatePropertyRequest.Validate if the designated constraints aren't met.
type CreatePropertyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreatePropertyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreatePropertyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreatePropertyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreatePropertyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreatePropertyRequestValidationError) ErrorName() string {
	return "CreatePropertyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreatePropertyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreatePropertyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreatePropertyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreatePropertyRequestValidationError{}

// Validate checks the field values on GetPropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPropertyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPropertyRequestMultiError, or nil if none found.
func (m *GetPropertyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPropertyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetPropertyId()); err != nil {
		err = GetPropertyRequestValidationError{
			field:  "PropertyId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetPropertyRequestMultiError(errors)
	}

	return nil
}

func (m *GetPropertyRequest) _validateUuid(uuid string) error {
	if matched := _property_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetPropertyRequestMultiError is an error wrapping multiple validation errors
// returned by GetPropertyRequest.ValidateAll() if the designated constraints
// aren't met.
type GetPropertyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPropertyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPropertyRequestMultiError) AllErrors() []error { return m }

// GetPropertyRequestValidationError is the validation error returned by
// GetPropertyRequest.Validate if the designated constraints aren't met.
type GetPropertyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPropertyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPropertyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPropertyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPropertyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPropertyRequestValidationError) ErrorName() string {
	return "GetPropertyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetPropertyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPropertyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPropertyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPropertyRequestValidationError{}

// Validate checks the field values on ListPropertiesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPropertiesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPropertiesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPropertiesRequestMultiError, or nil if none found.
func (m *ListPropertiesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPropertiesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFilter()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListPropertiesRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListPropertiesRequestValidationError{
					field:  "Filter",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilter()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListPropertiesRequestValidationError{
				field:  "Filter",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListPropertiesRequestMultiError(errors)
	}

	return nil
}

// ListPropertiesRequestMultiError is an error wrapping multiple validation
// errors returned by ListPropertiesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListPropertiesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPropertiesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPropertiesRequestMultiError) AllErrors() []error { return m }

// ListPropertiesRequestValidationError is the validation error returned by
// ListPropertiesRequest.Validate if the designated constraints aren't met.
type ListPropertiesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPropertiesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPropertiesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPropertiesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPropertiesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPropertiesRequestValidationError) ErrorName() string {
	return "ListPropertiesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListPropertiesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPropertiesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPropertiesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPropertiesRequestValidationError{}

// Validate checks the field values on ListPropertiesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPropertiesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPropertiesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPropertiesResponseMultiError, or nil if none found.
func (m *ListPropertiesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPropertiesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetProperties() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListPropertiesResponseValidationError{
						field:  fmt.Sprintf("Properties[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListPropertiesResponseValidationError{
						field:  fmt.Sprintf("Properties[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPropertiesResponseValidationError{
					field:  fmt.Sprintf("Properties[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListPropertiesResponseMultiError(errors)
	}

	return nil
}

// ListPropertiesResponseMultiError is an error wrapping multiple validation
// errors returned by ListPropertiesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListPropertiesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPropertiesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPropertiesResponseMultiError) AllErrors() []error { return m }

// ListPropertiesResponseValidationError is the validation error returned by
// ListPropertiesResponse.Validate if the designated constraints aren't met.
type ListPropertiesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPropertiesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPropertiesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPropertiesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPropertiesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPropertiesResponseValidationError) ErrorName() string {
	return "ListPropertiesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListPropertiesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPropertiesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPropertiesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPropertiesResponseValidationError{}

// Validate checks the field values on UpdatePropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdatePropertyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdatePropertyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdatePropertyRequestMultiError, or nil if none found.
func (m *UpdatePropertyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdatePropertyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetPropertyId()); err != nil {
		err = UpdatePropertyRequestValidationError{
			field:  "PropertyId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.Title != nil {
		// no validation rules for Title
	}

	if m.Description != nil {
		// no validation rules for Description
	}

	if m.Address != nil {
		// no validation rules for Address
	}

	if m.PropertyType != nil {
		// no validation rules for PropertyType
	}

	if m.Area != nil {
		// no validation rules for Area
	}

	if m.Price != nil {
		// no validation rules for Price
	}

	if m.Rooms != nil {
		// no validation rules for Rooms
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if m.OwnerUserId != nil {
		// no validation rules for OwnerUserId
	}

	if len(errors) > 0 {
		return UpdatePropertyRequestMultiError(errors)
	}

	return nil
}

func (m *UpdatePropertyRequest) _validateUuid(uuid string) error {
	if matched := _property_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// UpdatePropertyRequestMultiError is an error wrapping multiple validation
// errors returned by UpdatePropertyRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdatePropertyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdatePropertyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdatePropertyRequestMultiError) AllErrors() []error { return m }

// UpdatePropertyRequestValidationError is the validation error returned by
// UpdatePropertyRequest.Validate if the designated constraints aren't met.
type UpdatePropertyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdatePropertyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdatePropertyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdatePropertyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdatePropertyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdatePropertyRequestValidationError) ErrorName() string {
	return "UpdatePropertyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdatePropertyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdatePropertyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdatePropertyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdatePropertyRequestValidationError{}

// Validate checks the field values on PropertyResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PropertyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PropertyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PropertyResponseMultiError, or nil if none found.
func (m *PropertyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PropertyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProperty()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PropertyResponseValidationError{
					field:  "Property",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PropertyResponseValidationError{
					field:  "Property",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProperty()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PropertyResponseValidationError{
				field:  "Property",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PropertyResponseMultiError(errors)
	}

	return nil
}

// PropertyResponseMultiError is an error wrapping multiple validation errors
// returned by PropertyResponse.ValidateAll() if the designated constraints
// aren't met.
type PropertyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PropertyResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PropertyResponseMultiError) AllErrors() []error { return m }

// PropertyResponseValidationError is the validation error returned by
// PropertyResponse.Validate if the designated constraints aren't met.
type PropertyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PropertyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PropertyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PropertyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PropertyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PropertyResponseValidationError) ErrorName() string { return "PropertyResponseValidationError" }

// Error satisfies the builtin error interface
func (e PropertyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPropertyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PropertyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PropertyResponseValidationError{}

// Validate checks the field values on ListPropertiesRequest_Filter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPropertiesRequest_Filter) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPropertiesRequest_Filter with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPropertiesRequest_FilterMultiError, or nil if none found.
func (m *ListPropertiesRequest_Filter) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPropertiesRequest_Filter) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Status != nil {
		// no validation rules for Status
	}

	if m.OwnerUserId != nil {
		// no validation rules for OwnerUserId
	}

	if m.CreatedUserId != nil {
		// no validation rules for CreatedUserId
	}

	if m.PropertyType != nil {
		// no validation rules for PropertyType
	}

	if m.MinRooms != nil {
		// no validation rules for MinRooms
	}

	if m.MaxRooms != nil {
		// no validation rules for MaxRooms
	}

	if m.MinPrice != nil {
		// no validation rules for MinPrice
	}

	if m.MaxPrice != nil {
		// no validation rules for MaxPrice
	}

	if len(errors) > 0 {
		return ListPropertiesRequest_FilterMultiError(errors)
	}

	return nil
}

// ListPropertiesRequest_FilterMultiError is an error wrapping multiple
// validation errors returned by ListPropertiesRequest_Filter.ValidateAll() if
// the designated constraints aren't met.
type ListPropertiesRequest_FilterMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPropertiesRequest_FilterMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPropertiesRequest_FilterMultiError) AllErrors() []error { return m }

// ListPropertiesRequest_FilterValidationError is the validation error returned
// by ListPropertiesRequest_Filter.Validate if the designated constraints
// aren't met.
type ListPropertiesRequest_FilterValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPropertiesRequest_FilterValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPropertiesRequest_FilterValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPropertiesRequest_FilterValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPropertiesRequest_FilterValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPropertiesRequest_FilterValidationError) ErrorName() string {
	return "ListPropertiesRequest_FilterValidationError"
}

// Error satisfies the builtin error interface
func (e ListPropertiesRequest_FilterValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPropertiesRequest_Filter.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPropertiesRequest_FilterValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPropertiesRequest_FilterValidationError{}
